---
name: Build Action
on:
  pull_request:
    branches:
      - master
  release:
    types:
      - published
  push:
    branches:
      - master

jobs:
  draft:
    uses: metal-stack/actions-common/.github/workflows/release-drafter.yaml@v1

  go-build:
    uses: metal-stack/actions-common/.github/workflows/go-build-multiarch.yaml@multiarch-builds
    secrets: inherit
    with:
      platforms: |
        [
          {"platform": "linux/amd64", "goos": "linux", "goarch": "amd64", "runner": "ubuntu-latest"},
          {"platform": "linux/arm64", "goos": "linux", "goarch": "arm64", "runner": "ubuntu-26.04-arm"}
        ]
      build-command: make release GOARCH=$GOARCH
      artifact-files: |
        bin/
        nftables-exporter-linux-*.tgz

  release-assets:
    uses: metal-stack/actions-common/.github/workflows/release-assets.yaml@v1
    needs:
      - go-build
    with:
      artifact-ids: ${{ needs.go-build.outputs.go-build-artifacts }}
      files: |
        ./bin/*
        ./nftables-exporter-linux-*.tgz
